Remove options not common to all commands
OISF/suricata-update pull request #260
Opened 2020-10-09 16:02 UTC by TharushiJay

- [x] I have read the contributing guide lines at
  https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation
  contribution agreement at
  https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the
  changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3250

Describe changes:

Following the options mentioned in the docs, 
- Removed --version from global arguments and added to update arguments
- Removed --no-check-certificate from global arguments since it's not common to all commands

2020-10-14 21:59 UTC, jasonish commented on suricata/update/parsers.py
> +      'help': "Display version"}),
I think its OK to move `-V` here, but the check for this flag where it prints the version and exits will need to be changed as its not longer in the global arguments.  For example, this command fails now:
```
./bin/suricata-update
```

2020-10-14 22:01 UTC, jasonish requested changes

2020-10-14 22:01 UTC, jasonish commented on suricata/update/parsers.py
> -      'help': "Disable server SSL/TLS certificate verification"}),
I don't see this re-added anywhere.  It either needs to remain global, or added to any command that may go out on the network.

2020-10-15 08:25 UTC, TharushiJay commented
Closing this PR since it was advised to restrict the work to researching and finding the redundant options for all the commands.
Findings are presented at : https://redmine.openinfosecfoundation.org/issues/3250

2020-10-15 08:25 UTC, closed without merging