Lua file handler
OISF/suricata-update pull request #332
Opened 2023-10-16 09:08 UTC by naivling

Make sure these boxes are signed before submitting your Pull Request
-- thank you.

- [x ] I have read the contributing guide lines at
  https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ x] I have signed the Open Information Security Foundation
  contribution agreement at
  https://suricata-ids.org/about/contribution-agreement/

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:https://redmine.openinfosecfoundation.org/issues/6395

Describe changes:
I added the function handle_lua_rule_files, which obviously handles lua files shipped within a rule tarball.
It works nearly exactly the same as the existing functions handle_filehash_files and handle_dataset_files.
testing was done for nested and non nested archives, and for single and multiple occurances of  lua and luajit keywords  in rules.
It assumes the final outputdir is called "rules", but handle_filehash_files does the same, so this wont break setups not already broken.

2023-10-16 10:25 UTC, inashivb requested changes
Hi @naivling !
Thank you for your first contribution to our project. :)
Could you please
1. Squash the commits
2. Make the commit message like other commits in the repo
3. Add ticket number to the commit
4. Assign ticket to yourself on redmine

2023-10-17 07:17 UTC, naivling commented
Hi @inashivb
1 and 2 are done,
but I don't get, what you meant with
>     3. Add ticket number to the commit
Should I include it in the commit-message, or am I supposed to really commit  the ticket number in some way?

Sorry for the trouble, its my first PR in any project.

2023-10-17 07:30 UTC, inashivb commented
> Hi @inashivb 1 and 2 are done, but I don't get, what you meant with
> 
> > ```
> > 3. Add ticket number to the commit
> > ```
> 
> Should I include it in the commit-message, or am I supposed to really commit the ticket number in some way?
> 

Yes, please. In the commit message. Example: https://github.com/OISF/suricata-update/commit/93047464a5a141d95133ac2959d8daea307343bc

> Sorry for the trouble, its my first PR in any project.

No problem. :)

2023-10-18 08:32 UTC, naivling commented
After applying the requested changes to a new branch, this PR is now superseded by a [new one](https://github.com/OISF/suricata-update/pull/333)

2023-10-18 08:32 UTC, closed without merging